name: zoo_noises
description: A new Flutter project.

publish_to: "none"

version: 2.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.19.1
  cupertino_icons: ^1.0.2
  home_indicator: ^2.0.0
  fluttertoast: ^8.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    # IMAGES
    - assets/images/anteater.jpeg
    - assets/images/antelope.jpeg
    - assets/images/bear.jpeg
    # - assets/images/beluga.jpeg
    - assets/images/camel.jpeg
    - assets/images/cat.jpeg
    - assets/images/cougar.jpeg
    - assets/images/cheetah.jpeg
    - assets/images/dog.jpeg
    - assets/images/dolphin.jpeg
    - assets/images/dragon.jpeg
    - assets/images/dragon_2.jpeg
    - assets/images/eagle.jpeg
    - assets/images/elephant.jpeg
    - assets/images/falcon.jpeg
    - assets/images/frog.jpeg
    - assets/images/gorilla.jpeg
    - assets/images/hippo.jpeg
    # - assets/images/horse.jpeg
    - assets/images/iguana.jpeg
    - assets/images/jaguar.jpeg
    - assets/images/lamb.jpeg
    - assets/images/leopard.jpeg
    - assets/images/lion.jpeg
    - assets/images/moose.jpeg
    - assets/images/orca.jpeg
    - assets/images/otter.jpeg
    - assets/images/penguin.jpeg
    # - assets/images/pig.jpeg
    - assets/images/raccoon.jpeg
    - assets/images/sea-lion.jpeg
    - assets/images/seal.jpeg
    - assets/images/tiger.jpeg
    - assets/images/turkey.jpeg
    - assets/images/wolf.jpeg
    - assets/images/zebra.jpeg
    # assets/AUDIO
    - assets/audio/anteater.mp3
    - assets/audio/antelope.mp3
    - assets/audio/bear.mp3
    - assets/audio/beluga.mp3
    - assets/audio/camel.mp3
    - assets/audio/cat.mp3
    - assets/audio/cheetah.mp3
    - assets/audio/cougar.mp3
    - assets/audio/dog.mp3
    - assets/audio/dolphin.mp3
    - assets/audio/dragon.mp3
    - assets/audio/eagle.mp3
    - assets/audio/elephant.mp3
    - assets/audio/falcon.mp3
    - assets/audio/frog.mp3
    - assets/audio/gorilla.mp3
    - assets/audio/hippo.mp3
    - assets/audio/horse.mp3
    - assets/audio/iguana.mp3
    - assets/audio/jaguar.mp3
    - assets/audio/lamb.mp3
    - assets/audio/leopard.mp3
    - assets/audio/lion.mp3
    - assets/audio/moose.mp3
    - assets/audio/orca.mp3
    - assets/audio/otter.mp3
    - assets/audio/penguin.mp3
    - assets/audio/pig.mp3
    - assets/audio/raccoon.mp3
    - assets/audio/sea-lion.mp3
    - assets/audio/seal.mp3
    - assets/audio/tiger.mp3
    - assets/audio/turkey.mp3
    - assets/audio/wolf.mp3
    - assets/audio/zebra.mp3
